apiVersion: v1
kind: Service
metadata:
  name: flink-jobmanager-per-job
spec:
  type: ClusterIP
  ports:
  - name: rpc
    port: 6123
  - name: blob-server
    port: 6124
  - name: webui
    port: 8081
  selector:
    app: flink
    component: flink-jobmanager-per-job